Removed .ini file usage, changed data_types for `--add-extra-file-info`
SETI/rms-pds4indextools pull request #31
Opened 2024-07-17 00:18 UTC by esimpsons3ti

**1. Configuration Files**

- `INI` format is not longer required for configuration files. `YAML` is the new standard. Functions parsing and using the configuration file contents have been changed to use this new format.
- `--config-file` can now use multiple configuration files by being invoked multiple times in the query:
```
pds4_create_xml_index . "**/**/*.xml" --config-file config_1.yaml --generate-label ancillary --config-file label_config.yaml
```
- `--label-user-input` has been removed, now that `--config-file` has expanded functionality.
- Documentation for `--label-user-input` has been removed.
- Documentation for `--config-file` has been updated.
- Unit tests for the configuration files have been updated.

**2. Data Types Update**
- The data types for `filename` and `filepath` have been updated. `filename` now has the pds:ASCII_File_Name data type. `filepath` now has the `pds:ASCII_File_Specification_Name` data type if the value is less than or equal to 255 characters. If it is longer, an error message is printed and the program exits.

Fixes #24

2024-07-17 18:22 UTC, rfrenchseti requested changes

2024-07-17 19:44 UTC, esimpsons3ti commented on pds4indextools/pds4_create_xml_index.py
>      event a specified configuration file is given, the contents of that file will
Override or overwrite?

2024-07-17 19:51 UTC, rfrenchseti commented on pds4indextools/pds4_create_xml_index.py
>      event a specified configuration file is given, the contents of that file will
You could argue either way, but normally "override" means to take a part of something that's already there and change its behavior. So you have an existing configuration with many parameters, and you're overriding one of them. "Overwrite" means to take an existing configuration (or file) and replace it completely, not keeping what was there before. So I would use "override" in this case. In the previous case where we were replacing an entire file with a new file, we were "overwriting" it.

2024-07-17 20:20 UTC, esimpsons3ti commented on pds4indextools/pds4_create_xml_index.py
>      event a specified configuration file is given, the contents of that file will
Thank you for clarifying.

2024-07-17 20:43 UTC, esimpsons3ti commented on pds4indextools/pds4indextools.yaml
> +- pds:ASCII_Date_YMD: {
Oddly enough, `0001-01-01` is not interpreted as a string in the YAML file. It's as `datetime.date(1, 1, 1)`. Here's the failed unit test message:

```
 AssertionError: assert datetime.date(1, 1, 1) == '0001-01-01'
```

2024-07-17 20:53 UTC, rfrenchseti commented on pds4indextools/pds4indextools.yaml
> +- pds:ASCII_Date_YMD: {
Ah OK. That's something to mention in the documentation.

2024-07-18 01:58 UTC, rfrenchseti requested changes
This is nicely done and I only have minor comments. Rather than trying to write them all out, it was faster simply to make them myself. Please take a look at the diffs in my commit and see if there's anything you disagree with. Here is a summary:

- Removed the "Indices and tables" section from the main documentation page because those pages don't actually contain anything.
- Fixed a typo and added a few clickable links to the README file.
- According to the YAML syntax, `2020-01-01T00:00:00` is also supposed to be a datetime object. I'm not sure if this isn't crashing the code simply because you don't have a unit test for it, or whether it's because it isn't being parsed as a datetime. Nevertheless, for safety and consistency I put all date-time-like strings in quotes.
- I fixed a couple of bad indents in `index_label_template_pds.xml` that were flagged by VS Code.
- I fixed a bug in the actual tool where if you didn't specify both `nillable` and `label-contents` in a config file, it would crash.
- I also moved that update code out of the try/except block so that only the config file loading was inside the exception trap.
- I made a few minor modifications to the tool's main RST page, including:
  - Adding an Introduction header so the table of contents would look nicer
  - Changing the heading level of "Configuration Files" and its subheadings so the table of contents would look nicer
  - Adding an introductory paragraph to Configuration Files
  - Removing "Modification_History" from the list of classes, since it's not actually used
  - Updating the default config file contents
  - Adding an example of a label config file
  - Making a few minor wording changes

If you have no objection to my changes, I will go ahead and approve this PR.

2024-07-18 02:08 UTC, esimpsons3ti commented
I approve of your changes. Feel free to squash and merge.

2024-07-18 02:24 UTC, rfrenchseti approved these changes

2024-07-18 02:24 UTC, merged